//测试数据，数据并非完整，只验证功能
module.exports = [{
    "text": "北京市",
    "value": "110000",
    "children": [{
      "text": "北京市市辖区",
      "value": "110100",
      "children": [{
        "text": "东城区",
        "value": "110101"
      }, {
        "text": "西城区",
        "value": "110102"
      }, {
        "text": "朝阳区",
        "value": "110105"
      }]
    }]
  },
  {
    "text": "安徽省",
    "value": "340000",
    "children": [{
      "text": "合肥市",
      "value": "340100",
      "children": [{
        "text": "瑶海区",
        "value": "340102"
      }, {
        "text": "庐阳区",
        "value": "340103"
      }, {
        "text": "蜀山区",
        "value": "340104"
      }, {
        "text": "包河区",
        "value": "340111"
      }, {
        "text": "长丰县",
        "value": "340121"
      }, {
        "text": "肥东县",
        "value": "340122"
      }, {
        "text": "肥西县",
        "value": "340123"
      }, {
        "text": "庐江县",
        "value": "340124"
      }, {
        "text": "巢湖市",
        "value": "340181"
      }]
    }, {
      "text": "芜湖市",
      "value": "340200",
      "children": [{
        "text": "镜湖区",
        "value": "340202"
      }, {
        "text": "弋江区",
        "value": "340203"
      }, {
        "text": "鸠江区",
        "value": "340207"
      }, {
        "text": "三山区",
        "value": "340208"
      }, {
        "text": "芜湖县",
        "value": "340221"
      }, {
        "text": "繁昌县",
        "value": "340222"
      }, {
        "text": "南陵县",
        "value": "340223"
      }, {
        "text": "无为县",
        "value": "340225"
      }]
    }, {
      "text": "蚌埠市",
      "value": "340300",
      "children": [{
        "text": "龙子湖区",
        "value": "340302"
      }, {
        "text": "蚌山区",
        "value": "340303"
      }, {
        "text": "禹会区",
        "value": "340304"
      }, {
        "text": "淮上区",
        "value": "340311"
      }, {
        "text": "怀远县",
        "value": "340321"
      }, {
        "text": "五河县",
        "value": "340322"
      }, {
        "text": "固镇县",
        "value": "340323"
      }]
    }, {
      "text": "淮南市",
      "value": "340400",
      "children": [{
        "text": "大通区",
        "value": "340402"
      }, {
        "text": "田家庵区",
        "value": "340403"
      }, {
        "text": "谢家集区",
        "value": "340404"
      }, {
        "text": "八公山区",
        "value": "340405"
      }, {
        "text": "潘集区",
        "value": "340406"
      }, {
        "text": "凤台县",
        "value": "340421"
      }, {
        "text": "寿县",
        "value": "340422"
      }]
    }, {
      "text": "马鞍山市",
      "value": "340500",
      "children": [{
        "text": "花山区",
        "value": "340503"
      }, {
        "text": "雨山区",
        "value": "340504"
      }, {
        "text": "博望区",
        "value": "340506"
      }, {
        "text": "当涂县",
        "value": "340521"
      }, {
        "text": "含山县",
        "value": "340522"
      }, {
        "text": "和县",
        "value": "340523"
      }]
    }, {
      "text": "淮北市",
      "value": "340600",
      "children": [{
        "text": "杜集区",
        "value": "340602"
      }, {
        "text": "相山区",
        "value": "340603"
      }, {
        "text": "烈山区",
        "value": "340604"
      }, {
        "text": "濉溪县",
        "value": "340621"
      }]
    }, {
      "text": "铜陵市",
      "value": "340700",
      "children": [{
        "text": "铜官区",
        "value": "340705"
      }, {
        "text": "义安区",
        "value": "340706"
      }, {
        "text": "郊区",
        "value": "340711"
      }, {
        "text": "枞阳县",
        "value": "340722"
      }]
    }, {
      "text": "安庆市",
      "value": "340800",
      "children": [{
        "text": "迎江区",
        "value": "340802"
      }, {
        "text": "大观区",
        "value": "340803"
      }, {
        "text": "宜秀区",
        "value": "340811"
      }, {
        "text": "怀宁县",
        "value": "340822"
      }, {
        "text": "潜山县",
        "value": "340824"
      }, {
        "text": "太湖县",
        "value": "340825"
      }, {
        "text": "宿松县",
        "value": "340826"
      }, {
        "text": "望江县",
        "value": "340827"
      }, {
        "text": "岳西县",
        "value": "340828"
      }, {
        "text": "桐城市",
        "value": "340881"
      }]
    }, {
      "text": "黄山市",
      "value": "341000",
      "children": [{
        "text": "屯溪区",
        "value": "341002"
      }, {
        "text": "黄山区",
        "value": "341003"
      }, {
        "text": "徽州区",
        "value": "341004"
      }, {
        "text": "歙县",
        "value": "341021"
      }, {
        "text": "休宁县",
        "value": "341022"
      }, {
        "text": "黟县",
        "value": "341023"
      }, {
        "text": "祁门县",
        "value": "341024"
      }]
    }, {
      "text": "滁州市",
      "value": "341100",
      "children": [{
        "text": "琅琊区",
        "value": "341102"
      }, {
        "text": "南谯区",
        "value": "341103"
      }, {
        "text": "来安县",
        "value": "341122"
      }, {
        "text": "全椒县",
        "value": "341124"
      }, {
        "text": "定远县",
        "value": "341125"
      }, {
        "text": "凤阳县",
        "value": "341126"
      }, {
        "text": "天长市",
        "value": "341181"
      }, {
        "text": "明光市",
        "value": "341182"
      }]
    }, {
      "text": "阜阳市",
      "value": "341200",
      "children": [{
        "text": "颍州区",
        "value": "341202"
      }, {
        "text": "颍东区",
        "value": "341203"
      }, {
        "text": "颍泉区",
        "value": "341204"
      }, {
        "text": "临泉县",
        "value": "341221"
      }, {
        "text": "太和县",
        "value": "341222"
      }, {
        "text": "阜南县",
        "value": "341225"
      }, {
        "text": "颍上县",
        "value": "341226"
      }, {
        "text": "界首市",
        "value": "341282"
      }]
    }, {
      "text": "宿州市",
      "value": "341300",
      "children": [{
        "text": "埇桥区",
        "value": "341302"
      }, {
        "text": "砀山县",
        "value": "341321"
      }, {
        "text": "萧县",
        "value": "341322"
      }, {
        "text": "灵璧县",
        "value": "341323"
      }, {
        "text": "泗县",
        "value": "341324"
      }]
    }, {
      "text": "六安市",
      "value": "341500",
      "children": [{
        "text": "金安区",
        "value": "341502"
      }, {
        "text": "裕安区",
        "value": "341503"
      }, {
        "text": "叶集区",
        "value": "341504"
      }, {
        "text": "霍邱县",
        "value": "341522"
      }, {
        "text": "舒城县",
        "value": "341523"
      }, {
        "text": "金寨县",
        "value": "341524"
      }, {
        "text": "霍山县",
        "value": "341525"
      }]
    }, {
      "text": "亳州市",
      "value": "341600",
      "children": [{
        "text": "谯城区",
        "value": "341602"
      }, {
        "text": "涡阳县",
        "value": "341621"
      }, {
        "text": "蒙城县",
        "value": "341622"
      }, {
        "text": "利辛县",
        "value": "341623"
      }]
    }, {
      "text": "池州市",
      "value": "341700",
      "children": [{
        "text": "贵池区",
        "value": "341702"
      }, {
        "text": "东至县",
        "value": "341721"
      }, {
        "text": "石台县",
        "value": "341722"
      }, {
        "text": "青阳县",
        "value": "341723"
      }]
    }, {
      "text": "宣城市",
      "value": "341800",
      "children": [{
        "text": "宣州区",
        "value": "341802"
      }, {
        "text": "郎溪县",
        "value": "341821"
      }, {
        "text": "广德县",
        "value": "341822"
      }, {
        "text": "泾县",
        "value": "341823"
      }, {
        "text": "绩溪县",
        "value": "341824"
      }, {
        "text": "旌德县",
        "value": "341825"
      }, {
        "text": "宁国市",
        "value": "341881"
      }]
    }]
  }

];